const $=id=>document.getElementById(id),KEY='sleepTrackerDataV1';
let data=JSON.parse(localStorage.getItem(KEY)||'null')||{setup:false,settings:{lang:'ko',timezone:'Asia/Seoul',fixedWake:'06:30',window:5,lastBackup:null},logs:[]};
if(!Array.isArray(data.logs))data.logs=[];
if(!data.settings)data.settings={lang:'ko',timezone:'Asia/Seoul',fixedWake:'06:30',window:5,lastBackup:null};
let lang=data.settings.lang||'ko';
let editingId=null;
const save=()=>localStorage.setItem(KEY,JSON.stringify(data));
const t=(ko,en)=>lang==='ko'?ko:en;
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function translate(){document.documentElement.lang=lang;document.querySelectorAll('[data-ko]').forEach(el=>el.textContent=el.dataset[lang]);document.querySelectorAll('[data-placeholder-ko]').forEach(el=>el.placeholder=lang==='ko'?el.dataset.placeholderKo:el.dataset.placeholderEn);$('quickLang').textContent=lang==='ko'?'EN':'KO';$('language').value=lang;updateEditUI();setHeaderDate();render();}
const mins=x=>{let[h,m]=String(x||'00:00').split(':').map(Number);return h*60+m};
function to24(hour,minute,ampm){let h=Number(hour)%12;if(ampm==='PM')h+=12;return `${String(h).padStart(2,'0')}:${String(minute).padStart(2,'0')}`}
function from24(value){let[h,m]=String(value||'00:00').split(':').map(Number);return{hour:h%12||12,minute:m,ampm:h>=12?'PM':'AM'}}
function fmt(n){n=(n+1440)%1440;let h=Math.floor(n/60),m=n%60,ap=h>=12?'PM':'AM';return `${h%12||12}:${String(m).padStart(2,'0')} ${ap}`}
function buildPicker(name,value){const host=document.querySelector(`[data-time="${name}"]`),v=from24(value),hours=Array.from({length:12},(_,i)=>i+1),minutes=Array.from({length:60},(_,i)=>i);host.innerHTML=`<select class="tp-hour" aria-label="Hour">${hours.map(x=>`<option ${x===v.hour?'selected':''}>${x}</option>`).join('')}</select><select class="tp-minute" aria-label="Minute">${minutes.map(x=>`<option value="${x}" ${x===v.minute?'selected':''}>${String(x).padStart(2,'0')}</option>`).join('')}</select><select class="tp-ampm" aria-label="AM or PM"><option ${v.ampm==='AM'?'selected':''}>AM</option><option ${v.ampm==='PM'?'selected':''}>PM</option></select>`;host.querySelectorAll('select').forEach(x=>x.addEventListener('change',preview));}
function pickerValue(name){const h=document.querySelector(`[data-time="${name}"]`);return to24(h.querySelector('.tp-hour').value,h.querySelector('.tp-minute').value,h.querySelector('.tp-ampm').value)}
function calc(v){let tib=mins(v.wake)-mins(v.bed);if(tib<=0)tib+=1440;let tst=Math.max(0,Math.min(tib,tib-v.lat-v.waso));let eff=tib?Math.round(tst/tib*100):0;let behavior=Math.round((v.fresh+v.mood+(!v.caf?5:0)+(!v.alc?5:0)+(!v.nap?5:0)+(v.ex?5:0))/30*100);return{tib,tst,eff,behavior}}
function currentThought(){if(!$('thoughtEnabled').checked)return null;return{enabled:true,text:$('thoughtText').value.trim(),beliefBefore:+$('beliefBefore').value,emotion:$('emotion').value.trim(),emotionIntensity:+$('emotionIntensity').value||0,distortion:$('distortion').value,evidenceFor:$('evidenceFor').value.trim(),evidenceAgainst:$('evidenceAgainst').value.trim(),balanced:$('balancedThought').value.trim(),beliefAfter:+$('beliefAfter').value}}
function currentInput(){return{date:$('date').value,bed:pickerValue('bed'),wake:pickerValue('wake'),lat:+$('lat').value||0,aw:+$('aw').value||0,waso:+$('waso').value||0,fresh:+$('fresh').dataset.value,mood:+$('mood').dataset.value,caf:$('caf').checked,alc:$('alc').checked,nap:$('nap').checked,ex:$('ex').checked,share:$('share').checked,timezone:data.settings.timezone,hygiene:{schedule:$('hySchedule').checked,bedOnly:$('hyBedOnly').checked,comfortable:$('hyComfort').checked,windDown:$('hyWindDown').checked,screenLimit:$('hyScreen').checked},thought:currentThought()}}
function setHeaderDate(){let f=new Intl.DateTimeFormat(lang==='ko'?'ko-KR':'en-US',{timeZone:data.settings.timezone,weekday:'long',month:'long',day:'numeric'});$('headerDate').textContent=f.format(new Date())}
function setToday(){let parts=new Intl.DateTimeFormat('en-CA',{timeZone:data.settings.timezone,year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(new Date()),o={};parts.forEach(p=>o[p.type]=p.value);$('date').value=`${o.year}-${o.month}-${o.day}`}
function buildRatings(){['fresh','mood'].forEach(id=>{let host=$(id),v=Number(host.dataset.value||3);host.innerHTML=[1,2,3,4,5].map(n=>`<button type="button" data-score="${n}" class="${n===v?'selected':''}">${n}</button>`).join('');host.querySelectorAll('button').forEach(b=>b.onclick=()=>{host.dataset.value=b.dataset.score;buildRatings();preview()})})}
function go(id){document.querySelectorAll('.page').forEach(x=>x.classList.remove('active'));$(id).classList.add('active');document.querySelectorAll('.bottom-nav button').forEach(x=>x.classList.toggle('active',x.dataset.go===id));if(id==='home')render();window.scrollTo({top:0,behavior:'smooth'})}
document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>go(b.dataset.go));
document.querySelectorAll('[data-profile]').forEach(b=>b.onclick=()=>{let s=b.dataset.profile;data.setup=true;data.settings.lang=s==='seoul'?'ko':'en';data.settings.timezone=s==='seoul'?'Asia/Seoul':'America/Chicago';save();boot()});
$('quickLang').onclick=()=>{lang=lang==='ko'?'en':'ko';data.settings.lang=lang;save();translate()};
['lat','aw','waso','caf','alc','nap','ex'].forEach(id=>$(id).addEventListener('input',preview));
$('thoughtEnabled').addEventListener('change',()=>{$('thoughtFields').classList.toggle('hidden',!$('thoughtEnabled').checked)});
['beliefBefore','beliefAfter'].forEach(id=>$(id).addEventListener('input',()=>{$(id+'Out').textContent=$(id).value}));
function preview(){let c=calc(currentInput());$('preview').textContent=t(`침대 ${Math.floor(c.tib/60)}시간 ${c.tib%60}분 · 실제 수면 ${Math.floor(c.tst/60)}시간 ${c.tst%60}분 · 효율 ${c.eff}%`,`In bed ${Math.floor(c.tib/60)}h ${c.tib%60}m · Sleep ${Math.floor(c.tst/60)}h ${c.tst%60}m · Efficiency ${c.eff}%`)}
function updateEditUI(){let editing=editingId!==null;if($('cancelEdit'))$('cancelEdit').classList.toggle('hidden',!editing);if($('submitLog'))$('submitLog').textContent=editing?t('수정 내용 저장','Save changes'):t('수면 기록 저장','Save sleep log')}
function resetForm(){editingId=null;$('form').reset();$('fresh').dataset.value='3';$('mood').dataset.value='3';buildRatings();buildPicker('bed','23:00');buildPicker('wake',data.settings.fixedWake||'06:30');setToday();$('thoughtEnabled').checked=false;$('thoughtFields').classList.add('hidden');$('beliefBefore').value='5';$('beliefBeforeOut').textContent='5';$('beliefAfter').value='5';$('beliefAfterOut').textContent='5';updateEditUI();preview();}
function fillForm(x){editingId=x.id;$('date').value=x.date||'';buildPicker('bed',x.bed||'23:00');buildPicker('wake',x.wake||data.settings.fixedWake||'06:30');$('lat').value=x.lat||0;$('aw').value=x.aw||0;$('waso').value=x.waso||0;$('fresh').dataset.value=String(x.fresh||3);$('mood').dataset.value=String(x.mood||3);buildRatings();$('caf').checked=!!x.caf;$('alc').checked=!!x.alc;$('nap').checked=!!x.nap;$('ex').checked=!!x.ex;$('share').checked=!!x.share;let h=x.hygiene||{};$('hySchedule').checked=!!h.schedule;$('hyBedOnly').checked=!!h.bedOnly;$('hyComfort').checked=!!h.comfortable;$('hyWindDown').checked=!!h.windDown;$('hyScreen').checked=!!h.screenLimit;let th=x.thought||null;$('thoughtEnabled').checked=!!th;$('thoughtFields').classList.toggle('hidden',!th);$('thoughtText').value=th?.text||'';$('beliefBefore').value=th?.beliefBefore??5;$('beliefBeforeOut').textContent=$('beliefBefore').value;$('emotion').value=th?.emotion||'';$('emotionIntensity').value=th?.emotionIntensity??50;$('distortion').value=th?.distortion||'';$('evidenceFor').value=th?.evidenceFor||'';$('evidenceAgainst').value=th?.evidenceAgainst||'';$('balancedThought').value=th?.balanced||'';$('beliefAfter').value=th?.beliefAfter??5;$('beliefAfterOut').textContent=$('beliefAfter').value;updateEditUI();preview();go('log')}
function editLog(id){let x=data.logs.find(v=>v.id===id);if(x)fillForm(x)}
function deleteLog(id){let x=data.logs.find(v=>v.id===id);if(!x)return;if(!confirm(t('이 수면 기록을 삭제할까요? 삭제 후에는 백업 파일이 없다면 복구할 수 없습니다.','Delete this sleep log? It cannot be restored unless you have a backup.')))return;data.logs=data.logs.filter(v=>v.id!==id);if(editingId===id)resetForm();save();render()}
$('cancelEdit').onclick=()=>resetForm();
$('form').onsubmit=e=>{e.preventDefault();let v=currentInput(),c=calc(v),now=new Date().toISOString();if(editingId!==null){let i=data.logs.findIndex(x=>x.id===editingId);if(i>=0)data.logs[i]={...data.logs[i],...v,...c,updatedAt:now}}else{data.logs.push({...v,...c,id:Date.now(),createdAt:now})}data.logs.sort((a,b)=>a.date.localeCompare(b.date));save();resetForm();go('home')};
$('saveSettings').onclick=()=>{data.settings.lang=$('language').value;data.settings.timezone=$('timezone').value;data.settings.fixedWake=pickerValue('fixed');data.settings.window=Math.max(3,+$('window').value||5);lang=data.settings.lang;save();setToday();translate();alert(t('설정을 저장했습니다.','Settings saved.'))};
$('exportBtn').onclick=()=>{data.settings.lastBackup=new Date().toISOString();save();let blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`sleep-tracker-backup-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(a.href);renderBackup()};
$('importFile').onchange=async e=>{let f=e.target.files[0];if(!f)return;try{let obj=JSON.parse(await f.text());if(!obj.settings||!Array.isArray(obj.logs))throw 0;data=obj;lang=data.settings.lang||'ko';save();boot();alert(t('백업을 복원했습니다.','Backup restored.'))}catch{alert(t('올바른 백업 파일이 아닙니다.','Invalid backup file.'))}};
$('shareBtn').onclick=async()=>{let x=[...data.logs].reverse().find(v=>v.share);if(!x){alert(t('공유로 표시된 기록이 없습니다.','No log is marked for sharing.'));return}let text=t(`수면 기록 ${x.date}\n실제 수면 ${Math.floor(x.tst/60)}시간 ${x.tst%60}분\n침대 시간 ${Math.floor(x.tib/60)}시간 ${x.tib%60}분\n수면 효율 ${x.eff}%\n개운함 ${x.fresh}/5 · 기분 ${x.mood}/5`,`Sleep Log ${x.date}\nTotal sleep ${Math.floor(x.tst/60)}h ${x.tst%60}m\nTime in bed ${Math.floor(x.tib/60)}h ${x.tib%60}m\nSleep efficiency ${x.eff}%\nFreshness ${x.fresh}/5 · Mood ${x.mood}/5`);if(navigator.share)await navigator.share({title:'Sleep Tracker',text});else{await navigator.clipboard.writeText(text);alert(t('공유 내용을 복사했습니다.','Share text copied.'))}};
function renderBackup(){let b=data.settings.lastBackup;$('backupStatus').textContent=b?t(`마지막 백업: ${new Date(b).toLocaleDateString('ko-KR')}`,`Last backup: ${new Date(b).toLocaleDateString('en-US')}`):t('아직 백업하지 않았습니다.','No backup yet.')}
function lineChart(c,vals){let ctx=c.getContext('2d'),w=c.clientWidth,h=190,dpr=devicePixelRatio||1;c.width=w*dpr;c.height=h*dpr;ctx.scale(dpr,dpr);ctx.clearRect(0,0,w,h);ctx.strokeStyle='#dce8f3';ctx.lineWidth=1;[0,1,2,3].forEach(i=>{let y=18+i*(h-36)/3;ctx.beginPath();ctx.moveTo(8,y);ctx.lineTo(w-8,y);ctx.stroke()});if(!vals.length)return;ctx.strokeStyle='#347fca';ctx.lineWidth=3;ctx.lineCap='round';ctx.lineJoin='round';ctx.beginPath();vals.forEach((v,i)=>{let x=12+(w-24)*(vals.length===1?.5:i/(vals.length-1)),y=18+(h-36)*(1-v/100);i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.stroke();ctx.fillStyle='#1d568a';vals.forEach((v,i)=>{let x=12+(w-24)*(vals.length===1?.5:i/(vals.length-1)),y=18+(h-36)*(1-v/100);ctx.beginPath();ctx.arc(x,y,3.5,0,Math.PI*2);ctx.fill()})}
function barChart(c,logs){let ctx=c.getContext('2d'),w=c.clientWidth,h=190,dpr=devicePixelRatio||1;c.width=w*dpr;c.height=h*dpr;ctx.scale(dpr,dpr);ctx.clearRect(0,0,w,h);if(!logs.length)return;let max=Math.max(...logs.map(x=>x.tib),480),slot=(w-16)/logs.length;logs.forEach((x,i)=>{let x0=8+i*slot,bw=Math.max(3,slot*.27),a=(h-20)*x.tib/max,b=(h-20)*x.tst/max;ctx.fillStyle='#b9d9f2';ctx.fillRect(x0,h-10-a,bw,a);ctx.fillStyle='#347fca';ctx.fillRect(x0+bw+2,h-10-b,bw,b)})}
function patternInsight(logs){if(logs.length<5)return t('기록이 5회 이상 쌓이면 생활습관과 수면효율 사이의 반복되는 패턴을 간단히 보여드릴게요.','After 5 or more logs, this section will summarize simple recurring associations between habits and sleep efficiency.');let checks=[['caf',t('카페인','caffeine')],['alc',t('음주','alcohol')],['nap',t('낮잠','naps')],['ex',t('운동','exercise')]];for(let [key,label] of checks){let yes=logs.filter(x=>x[key]===true),no=logs.filter(x=>x[key]===false);if(yes.length>=2&&no.length>=2){let ay=Math.round(yes.reduce((s,x)=>s+x.eff,0)/yes.length),an=Math.round(no.reduce((s,x)=>s+x.eff,0)/no.length),diff=ay-an;if(Math.abs(diff)>=5)return diff<0?t(`${label}이(가) 기록된 날의 평균 수면효율이 그렇지 않은 날보다 ${Math.abs(diff)}%p 낮게 나타났습니다.`,`Average sleep efficiency was ${Math.abs(diff)} percentage points lower on days with ${label} in your logs.`):t(`${label}이(가) 기록된 날의 평균 수면효율이 그렇지 않은 날보다 ${Math.abs(diff)}%p 높게 나타났습니다.`,`Average sleep efficiency was ${Math.abs(diff)} percentage points higher on days with ${label} in your logs.`)}}return t('현재 기록에서는 생활습관에 따른 뚜렷한 수면효율 차이가 아직 보이지 않습니다.','Your current logs do not yet show a clear sleep-efficiency difference by tracked habit.')}
function render(){let logs=[...data.logs].sort((a,b)=>a.date.localeCompare(b.date)),n=Math.max(3,data.settings.window||5),recent=logs.slice(-n),avg=recent.length?Math.round(recent.reduce((s,x)=>s+x.tst,0)/recent.length):null,avgLat=recent.length?Math.round(recent.reduce((s,x)=>s+(x.lat||0),0)/recent.length):null;$('avg').textContent=avg!=null?`${Math.floor(avg/60)}h ${avg%60}m`:'--';$('avgLatency').textContent=avgLat!=null?`${avgLat}m`:'--';if(recent.length>=n&&avg!=null){$('rec').textContent=fmt(mins(data.settings.fixedWake)-avg);$('basis').textContent=t(`최근 ${n}회 실제 수면시간 평균을 고정 기상시간에서 역산한 추정치입니다.`,`Estimate based on your fixed wake time minus average total sleep time from the last ${n} logs.`)}else{$('rec').textContent='--:--';$('basis').textContent=t(`취침 제안까지 ${n-recent.length}회 기록이 더 필요합니다.`,`Add ${n-recent.length} more log${n-recent.length===1?'':'s'} before a bedtime estimate is shown.`)}let last=logs.at(-1);$('eff').textContent=last?`${last.eff}%`:'--';$('recent').innerHTML=logs.slice(-7).reverse().map(x=>`<div class="recent-item"><div class="recent-main"><div><b>${esc(x.date)}</b><small>${fmt(mins(x.bed))} → ${fmt(mins(x.wake))}${x.share?t(' · 공유',' · shared'):''}</small></div><div class="recent-values"><b>${x.eff}%</b><small>${Math.floor(x.tst/60)}h ${x.tst%60}m</small></div></div><div class="record-actions"><button type="button" data-edit="${x.id}">${t('수정','Edit')}</button><button type="button" class="delete-action" data-delete="${x.id}">${t('삭제','Delete')}</button></div></div>`).join('')||`<p class="muted">${t('첫 수면 기록을 추가해보세요.','Add your first sleep log.')}</p>`;$('recent').querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>editLog(Number(b.dataset.edit)));$('recent').querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>deleteLog(Number(b.dataset.delete)));$('patternInsight').textContent=patternInsight(logs.slice(-30));lineChart($('chart1'),logs.slice(-14).map(x=>x.eff));barChart($('chart2'),logs.slice(-14));renderBackup()}
function boot(){if(!data.setup){$('welcome').classList.remove('hidden');$('app').classList.add('hidden');return}$('welcome').classList.add('hidden');$('app').classList.remove('hidden');lang=data.settings.lang||'ko';$('language').value=lang;$('timezone').value=data.settings.timezone;$('window').value=data.settings.window||5;buildPicker('bed','23:00');buildPicker('wake',data.settings.fixedWake||'06:30');buildPicker('fixed',data.settings.fixedWake||'06:30');buildRatings();setToday();setHeaderDate();translate();preview()}
window.addEventListener('resize',render);boot();if('serviceWorker'in navigator&&location.protocol.startsWith('http'))navigator.serviceWorker.register('./service-worker.js');
