const $=id=>document.getElementById(id), KEY='sleepTrackerDataV1';
let data=JSON.parse(localStorage.getItem(KEY)||'null')||{setup:false,settings:{lang:'ko',timezone:'Asia/Seoul',fixedWake:'06:30',window:5,lastBackup:null},logs:[],exercises:[]};
let lang=data.settings.lang||'ko';
function save(){localStorage.setItem(KEY,JSON.stringify(data))}
function t(ko,en){return lang==='ko'?ko:en}
function translate(){document.documentElement.lang=lang;document.querySelectorAll('[data-ko]').forEach(el=>el.textContent=el.dataset[lang]);$('quickLang').textContent=lang==='ko'?'EN':'한';$('language').value=lang}
function mins(x){const [h,m]=x.split(':').map(Number);return h*60+m}
function fmt(n){n=(n+1440)%1440;let h=Math.floor(n/60),m=n%60;if(lang==='ko')return `${String(h).padStart(2,'0')}:${String(m).padStart(2,'0')}`;let ap=h>=12?'PM':'AM',hh=h%12||12;return `${hh}:${String(m).padStart(2,'0')} ${ap}`}
function calc(v){let tib=mins(v.wake)-mins(v.bed);if(tib<=0)tib+=1440;let tst=tib-v.lat-v.waso;if(tst<0)tst=0;if(tst>tib)tst=tib;let eff=tib?Math.round(tst/tib*100):0;let behavior=Math.round((v.fresh+v.mood+(!v.caf?5:0)+(!v.alc?5:0)+(!v.nap?5:0)+(v.ex?5:0))/30*100);return{tib,tst,eff,behavior}}
function currentInput(){return{date:$('date').value,bed:$('bed').value,wake:$('wake').value,lat:+$('lat').value||0,aw:+$('aw').value||0,waso:+$('waso').value||0,fresh:+$('fresh').value,mood:+$('mood').value,caf:$('caf').checked,alc:$('alc').checked,nap:$('nap').checked,ex:$('ex').checked,share:$('share').checked,timezone:data.settings.timezone}}
function go(id){document.querySelectorAll('.page').forEach(x=>x.classList.remove('active'));$(id).classList.add('active');document.querySelectorAll('.nav button').forEach(x=>x.classList.toggle('active',x.dataset.go===id));if(id==='home')render();if(id==='tools')renderExercises()}
document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>go(b.dataset.go));
document.querySelectorAll('[data-profile]').forEach(b=>b.onclick=()=>{let s=b.dataset.profile;data.setup=true;data.settings.lang=s==='seoul'?'ko':'en';data.settings.timezone=s==='seoul'?'Asia/Seoul':'America/Chicago';save();boot()});
$('quickLang').onclick=()=>{lang=lang==='ko'?'en':'ko';data.settings.lang=lang;save();translate();render()};
['bed','wake','lat','waso','fresh','mood','caf','alc','nap','ex'].forEach(id=>$(id).addEventListener('input',preview));
function preview(){let v=currentInput();if(!v.bed||!v.wake){$('preview').textContent=t('시간을 입력하면 자동 계산됩니다.','Enter times to see automatic calculations.');return}let c=calc(v);$('preview').textContent=t(`침대 ${Math.floor(c.tib/60)}시간 ${c.tib%60}분 · 실제 수면 ${Math.floor(c.tst/60)}시간 ${c.tst%60}분 · 효율 ${c.eff}% · 행동점수 ${c.behavior}`,`In bed ${Math.floor(c.tib/60)}h ${c.tib%60}m · Sleep ${Math.floor(c.tst/60)}h ${c.tst%60}m · Efficiency ${c.eff}% · Behavior ${c.behavior}`)}
$('form').onsubmit=e=>{e.preventDefault();let v=currentInput();if(!v.date||!v.bed||!v.wake)return;let c=calc(v);data.logs.push({...v,...c,id:Date.now(),createdAt:new Date().toISOString()});data.logs.sort((a,b)=>a.date.localeCompare(b.date));save();e.target.reset();$('fresh').value=3;$('mood').value=3;setToday();preview();go('home')};
function setToday(){let d=new Intl.DateTimeFormat('en-CA',{timeZone:data.settings.timezone,year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());$('date').value=d}
$('saveTool').onclick=()=>{data.exercises.push({id:Date.now(),date:new Date().toISOString(),thought:$('thought').value,error:$('error').value,for:$('for').value,against:$('against').value,alt:$('alt').value,opp:$('opp').value,share:$('toolShare').checked});save();['thought','for','against','alt','opp'].forEach(id=>$(id).value='');$('error').value='';$('toolShare').checked=false;renderExercises()};
function renderExercises(){$('exercises').innerHTML=data.exercises.slice().reverse().map(x=>`<div class="item"><b>${new Date(x.date).toLocaleDateString(lang==='ko'?'ko-KR':'en-US')}</b>${x.share?' · ↗':''}<div>${esc(x.thought||x.alt||'-')}</div></div>`).join('')||`<p class="muted">${t('아직 저장된 연습이 없습니다.','No saved exercises yet.')}</p>`}
$('saveSettings').onclick=()=>{data.settings.lang=$('language').value;data.settings.timezone=$('timezone').value;data.settings.fixedWake=$('fixed').value;data.settings.window=Math.max(1,+$('window').value||5);lang=data.settings.lang;save();setToday();translate();render();alert(t('설정을 저장했습니다.','Settings saved.'))};
$('exportBtn').onclick=()=>{data.settings.lastBackup=new Date().toISOString();save();let blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`sleep-tracker-backup-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(a.href);renderBackup()};
$('importFile').onchange=async e=>{let f=e.target.files[0];if(!f)return;try{let obj=JSON.parse(await f.text());if(!obj.settings||!Array.isArray(obj.logs))throw 0;data=obj;lang=data.settings.lang||'ko';save();boot();alert(t('백업을 복원했습니다.','Backup restored.'))}catch{alert(t('올바른 백업 파일이 아닙니다.','Invalid backup file.'))}};
$('shareBtn').onclick=async()=>{let x=[...data.logs].reverse().find(v=>v.share);if(!x){alert(t('공유로 표시된 기록이 없습니다.','No log is marked for sharing.'));return}let text=t(`🌙 수면 기록 ${x.date}\n실제 수면 ${Math.floor(x.tst/60)}시간 ${x.tst%60}분\n침대 시간 ${Math.floor(x.tib/60)}시간 ${x.tib%60}분\n수면 효율 ${x.eff}%\n개운함 ${x.fresh}/5 · 기분 ${x.mood}/5`,`🌙 Sleep Log ${x.date}\nTotal sleep ${Math.floor(x.tst/60)}h ${x.tst%60}m\nTime in bed ${Math.floor(x.tib/60)}h ${x.tib%60}m\nSleep efficiency ${x.eff}%\nFreshness ${x.fresh}/5 · Mood ${x.mood}/5`);if(navigator.share)await navigator.share({title:'Sleep Tracker',text});else{await navigator.clipboard.writeText(text);alert(t('공유 내용을 복사했습니다.','Share text copied.'))}};
function esc(s){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function render(){let logs=[...data.logs].sort((a,b)=>a.date.localeCompare(b.date)),n=data.settings.window||5,recent=logs.slice(-n),avg=recent.length?Math.round(recent.reduce((s,x)=>s+x.tst,0)/recent.length):null;if(avg!=null){$('avg').textContent=`${Math.floor(avg/60)}h ${avg%60}m`;$('rec').textContent=fmt(mins(data.settings.fixedWake)-avg);$('basis').textContent=t(`최근 ${recent.length}회 평균 실제 수면시간 기준`,`Based on ${recent.length} recent sleep logs`)}else{$('avg').textContent='--';$('rec').textContent='--:--';$('basis').textContent=t('수면 기록이 쌓이면 계산됩니다.','Calculated after sleep logs are added.')}let last=logs.at(-1);$('eff').textContent=last?`${last.eff}%`:'--';$('beh').textContent=last?`${last.behavior}`:'--';$('recent').innerHTML=logs.slice(-7).reverse().map(x=>`<div class="item"><div class="head"><b>${x.date}</b><span>${x.share?'↗ ':''}${x.eff}%</span></div><div class="chips"><span class="chip">${Math.floor(x.tst/60)}h ${x.tst%60}m</span><span class="chip">${t('개운함','Fresh')} ${x.fresh}/5</span><span class="chip">${t('기분','Mood')} ${x.mood}/5</span></div></div>`).join('')||`<p class="muted">${t('첫 수면 기록을 추가해보세요.','Add your first sleep log.')}</p>`;drawCharts(logs.slice(-14));renderBackup()}
function renderBackup(){let b=data.settings.lastBackup;$('backupStatus').textContent=b?t(`마지막 백업: ${new Date(b).toLocaleDateString('ko-KR')}`,`Last backup: ${new Date(b).toLocaleDateString('en-US')}`):t('아직 백업하지 않았습니다.','No backup yet.')}
function lineChart(canvas,vals,min=0,max=100){let c=canvas,ctx=c.getContext('2d'),w=c.clientWidth,h=190,dpr=devicePixelRatio||1;c.width=w*dpr;c.height=h*dpr;ctx.scale(dpr,dpr);ctx.clearRect(0,0,w,h);ctx.strokeStyle='#d9e8f5';ctx.lineWidth=1;for(let i=0;i<4;i++){let y=20+i*(h-40)/3;ctx.beginPath();ctx.moveTo(25,y);ctx.lineTo(w-10,y);ctx.stroke()}if(vals.length<1)return;ctx.strokeStyle='#4d91d8';ctx.lineWidth=3;ctx.beginPath();vals.forEach((v,i)=>{let x=30+(w-50)*(vals.length===1?.5:i/(vals.length-1)),y=20+(h-40)*(1-(v-min)/(max-min));i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.stroke();ctx.fillStyle='#2d608f';vals.forEach((v,i)=>{let x=30+(w-50)*(vals.length===1?.5:i/(vals.length-1)),y=20+(h-40)*(1-(v-min)/(max-min));ctx.beginPath();ctx.arc(x,y,3.5,0,Math.PI*2);ctx.fill()})}
function barChart(canvas,logs){let c=canvas,ctx=c.getContext('2d'),w=c.clientWidth,h=190,dpr=devicePixelRatio||1;c.width=w*dpr;c.height=h*dpr;ctx.scale(dpr,dpr);ctx.clearRect(0,0,w,h);if(!logs.length)return;let max=Math.max(...logs.map(x=>x.tib),480),slot=(w-35)/logs.length;logs.forEach((x,i)=>{let x0=25+i*slot,bw=Math.max(3,slot*.28),a=(h-25)*x.tib/max,b=(h-25)*x.tst/max;ctx.fillStyle='#b9d9f2';ctx.fillRect(x0,h-15-a,bw,a);ctx.fillStyle='#4d91d8';ctx.fillRect(x0+bw+2,h-15-b,bw,b)})}
function drawCharts(logs){lineChart($('chart1'),logs.map(x=>x.eff),0,100);barChart($('chart2'),logs)}
function boot(){if(!data.setup){$('welcome').classList.remove('hidden');$('app').classList.add('hidden');return}$('welcome').classList.add('hidden');$('app').classList.remove('hidden');lang=data.settings.lang||'ko';$('language').value=lang;$('timezone').value=data.settings.timezone;$('fixed').value=data.settings.fixedWake;$('window').value=data.settings.window;setToday();translate();preview();render();renderExercises()}
window.addEventListener('resize',()=>render());boot();
if('serviceWorker'in navigator&&location.protocol.startsWith('http'))navigator.serviceWorker.register('./service-worker.js');
